apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    env: k-test
    app: myapp
  #namespace: K-test
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres