apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k-test
resources:
- namespace.yaml
- db-configmap.yaml
- db-deployment.yaml
- db-secret.yaml
- myapp-secret.yaml
- todoapp-configmap.yaml
- todoapp-deployment.yaml
- volume.yaml