apiVersion: v1
kind: ConfigMap
metadata:
  name: todoapp-config
  labels:
    env: k-test
  #namespace: K-test
data:
  DB_ENGINE: django.db.backends.postgresql
  DB_HOST: my-postgres
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_PORT: "5432"
  
