---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  #namespace: K-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storage
  resources:
    requests:
      storage: 200Mi   # Corrected to match the PersistentVolume

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage
  labels:
     app: tododb
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 200Mi  # Matches the claim
  storageClassName: postgres-storage
  hostPath:
    path: "/mnt/data/postgres-data"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage
provisioner: kubernetes.io/host-path
reclaimPolicy: Retain
volumeBindingMode: Immediate
